# Generated by Django 4.1.5 on 2023-02-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('text', models.CharField(default='', max_length=3000)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_comment', to='core.post')),
            ],
        ),
    ]
