# Generated by Django 4.1.5 on 2023-02-07 01:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
